### ISSUE TITLE
Thanks so much for doing this!

### ISSUE THREAD

**Issue by derrickbeining** [tssm/up-to-date-real-world-haskell#12]
That is all ❤️

**Comment by bradrn** [comment]
I concur. I've always thought that Real World Haskell is a wonderful resource, but it's a pity that it's usefulness is limited due to its age.

(Oh, by the way: why don't you post a link to this project to the [Haskell subreddit](https://www.reddit.com/r/haskell/)? In my opinion, that would be a good opportunity to showcase this project to the wider Haskell community.)
